name: CI

on:
  push:
    branches: [ main ]

jobs:
  linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test with gcc
        env:
          CC: gcc
        run: make coverage
      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  linux-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test with clang
        env:
          CC: clang
        run: make test
