name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: 'make test CC=${{ matrix.compiler }}'
