name: CI

on:
  push:
    branches: [ main ]

jobs:
  test-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: gcc
        run: 'make coverage CC=gcc'
      - name: upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  test-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: clang
        run: 'make test CC=clang'
